#!/data/data/com.termux/files/usr/bin/bash
 
RED='\e[0;31m'
WHITE='\e[0;37m'
BLUE='\e[0;34m'
YELLOW='\e[0;33m'
GREEN='\e[32m'
PURPLE='\e[1;95m'
RESET='\e[0m'
 
clear
 
echo -e " "
echo -e "
 ${GREEN}YouTube-DLP will now be installed.
 
 YouTube-DLP support's downloading video and 
 audio from 100's of websites.
 
 When asked for any user conformation during 
 the installation, type Y and press ENTER.\n"
 
read -p " Press ENTER to continue:-"
clear
 
echo " "
echo -e "${GREEN}Upgrading Packages:-${RESET}"
echo " "
apt update --assume-yes && apt upgrade --assume-yes
 
echo " "
echo -e "${GREEN}Installing FFmpeg:-${RESET}\n"
pkg install -y ffmpeg
 
echo " "
echo -e "${GREEN}Installing Python:-${RESET}\n"
pkg install -y python
 
echo " "
echo -e "${GREEN}Updating Python:-${RESET}\n"
python -m pip install --upgrade pip setuptools wheel
 
echo " "
echo -e "${GREEN}Installing YouTube-DLP:-${RESET}\n"
yes | python3 -m pip install -U yt-dlp
 
echo " "
echo -e "${GREEN}Creating YT-DLP bin folder:-${RESET}\n"
mkdir ~/bin
 
echo " "
echo -e "${GREEN}Installing Termux-URL-Opener:-${RESET}\n"
curl https://raw.githubusercontent.com/6060842/YTdlpTermux/main/YT-DLP-02 -o ~/bin/termux-url-opener
dos2unix ~/bin/termux-url-opener

echo " "
echo -e "${GREEN}Installing Termux API:-${RESET}\n"
pkg install termux-api
 
clear

echo -e "${GREEN} Select allow on the next prompt for 
 storage access permission.\n"
read -p " Press ENTER to continue:-"
clear
termux-setup-storage
sleep 5

clear

echo " "
echo -e "${GREEN} Select Termux for draw over apps permission 
 on the next prompt & allow the permission.
 Then press back to return to Termux\n"
read -p " Press ENTER to continue:-"
`am start --user 0 -a android.settings.action.MANAGE_OVERLAY_PERMISSION -d "package:com.termux"`
 
clear
 
echo " "
echo -e "
 ${RED}YouTube-DLP is now installed, download
 video and audio from 100's of web sites.${RESET}
 
 ${WHITE}Share to Termux from Android share menu 
 to save video or audio to Downloads\Media.${RESET}
 
${BLUE} For more info visit github.com/6060842${RESET}
 ${BLUE}Type EXIT and press ENTER to leave Termux:-\n"
